### PR TITLE
fix some tiny mistakes about class and iterator regex

### PR DESCRIPTION
**Pull request by hikerpig**

### CODE REVIEW

**Comment by lukaszkorecki** [comment]
hi @hikerpig - could you add some tests for these changes?

Looks like these regexes are pretty crucial so it would be great to increase the coverage on them

**Comment by hikerpig** [comment]
See my new commit.
B.T.W  can't help to fix a syntax error in spec/fixtures/test.coffee

**Comment by lukaszkorecki** [comment]
@hikerpig that's looks great. I'm going to release the new version of the gem today

**Comment by lukaszkorecki** [comment]
@hikerpig v0.5.1 of CoffeeTags has been released. Enjoy!

**Pull request merged**
